name: "Secret Scanning"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  check_commits:
    runs-on: ubuntu-latest
    steps:
    - name: Set depth and branch variables
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          echo "depth=$(($(jq length <<< '${{ toJson(github.event.commits) }}') + 2))" >> $GITHUB_ENV
          echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
        fi
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "depth=$((${{ github.event.pull_request.commits }}+2))" >> $GITHUB_ENV
          echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
        fi
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{env.branch}}
        fetch-depth: ${{env.depth}}
    - uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown
