name: "Secret Scanning"
on:
  push:

jobs:
  check_commits:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown
